language: go
sudo: false
go:
  - 1.8
before_script:
  - export QBOXROOT=$TRAVIS_BUILD_DIR/../..
script:
  - cd $QBOXROOT
  - export QBOXROOT=$(pwd)
  - git clone git@github.com:qbox/base.git
  - cd $QBOXROOT/base
  - source env.sh
  - mkdir $QBOXROOT/../qiniu.com/
  - mv $TRAVIS_BUILD_DIR $QBOXROOT/../qiniu.com/
  - go get -u github.com/kardianos/govendor
  - cd $QBOXROOT/../qiniu.com/report/TiDB/src/qiniu.com/biserver
  - export DEFAULT_EXCEPT_PKGS=vendor
  - if [[ $GOPATH == :* ]]; then export GOPATH=`echo $GOPATH | sed "s/://"`; fi
  - go get github.com/pingcap/tidb
  - go get github.com/XeLabs/go-mysqlstack
  - go get github.com/go-sql-driver/mysql
  - if [[ "$TRAVIS_BRANCH" == "develop" ]]; then make gotest; else make test; fi